steps:

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-f','./Dockerfile', '-t', 'gcr.io/$PROJECT_ID/tandur-backend-images/tandur-backend:$SHORT_SHA', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/tandur-backend-images/tandur-backend:$SHORT_SHA']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'tandur-backend', '--image=gcr.io/$PROJECT_ID/tandur-backend-images/tandur-backend:$SHORT_SHA']

images:
- gcr.io/$PROJECT_ID/tandur-backend-images/tandur-backend:$SHORT_SHA